spring.application.name=homestore
server.port=8081

# Recargar plantillas Thymeleaf sin reiniciar
spring.thymeleaf.cache=false

# Conexión a MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/homestoredb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# Validar el esquema de la base de datos al iniciar la aplicación, en lugar de crear o actualizar automáticamente las tablas.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs
logging.level.root=INFO
logging.level.com.ufide.homestore=DEBUG

spring.profiles.include=local

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

server.forward-headers-strategy=framework
